/*
 * Audio Delay Effect for File Playback using Teensy 4.1
 * Version 1.0
 *
 * Author: Rafael Sabe
 * Email: rafaelmsabe@gmail.com
 */

#ifndef AUDIODELAYPB_DEF_H
#define AUDIODELAYPB_DEF_H

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

/*GLOBAL AUDIO DEFINITIONS*/
#define AUDIO_BITDEPTH 16U
#define AUDIO_NCHANNELS 2U

/*DELAY DSP BUFFER DEFINITIONS*/
#define DSPBUFFER_SIZE_FRAMES 16384U
#define DSPBUFFER_SIZE_SAMPLES (DSPBUFFER_SIZE_FRAMES*AUDIO_NCHANNELS)
#define DSPBUFFER_SIZE_BYTES (DSPBUFFER_SIZE_SAMPLES*sizeof(float))

/*AUDIO BUFFER DEFINITIONS*/
#define AUDIOBUFFER_SEGMENT_SIZE_FRAMES 128U
#define AUDIOBUFFER_SEGMENT_SIZE_SAMPLES (AUDIOBUFFER_SEGMENT_SIZE_FRAMES*AUDIO_NCHANNELS)
#define AUDIOBUFFER_SEGMENT_SIZE_BYTES (AUDIOBUFFER_SEGMENT_SIZE_SAMPLES*AUDIO_BITDEPTH/8U)

#define AUDIOBUFFER_N_SEGMENTS 4U

#define AUDIOBUFFER_SIZE_FRAMES (AUDIOBUFFER_SEGMENT_SIZE_FRAMES*AUDIOBUFFER_N_SEGMENTS)
#define AUDIOBUFFER_SIZE_SAMPLES (AUDIOBUFFER_SIZE_FRAMES*AUDIO_NCHANNELS)
#define AUDIOBUFFER_SIZE_BYTES (AUDIOBUFFER_SIZE_SAMPLES*AUDIO_BITDEPTH/8U)

/*DELAY DSP BUFFER SEGMENT DEFINITIONS*/
#define DSPBUFFER_SEGMENT_SIZE_FRAMES AUDIOBUFFER_SEGMENT_SIZE_FRAMES
#define DSPBUFFER_SEGMENT_SIZE_SAMPLES (DSPBUFFER_SEGMENT_SIZE_FRAMES*AUDIO_NCHANNELS)
#define DSPBUFFER_SEGMENT_SIZE_BYTES (DSPBUFFER_SEGMENT_SIZE_SAMPLES*sizeof(float))

#define DSPBUFFER_N_SEGMENTS (DSPBUFFER_SIZE_FRAMES/DSPBUFFER_SEGMENT_SIZE_FRAMES)

/*I2S DMA CHANNEL DEFINITIONS*/
#define DMA_I2S_TRANSFER_SIZE_BYTES (AUDIOBUFFER_SEGMENT_SIZE_BYTES)
#define DMA_I2S_TRANSFER_SIZE_SAMPLES (DMA_I2S_TRANSFER_SIZE_BYTES*8U/AUDIO_BITDEPTH)
#define DMA_I2S_TRANSFER_SIZE_FRAMES (DMA_I2S_TRANSFER_SIZE_SAMPLES/AUDIO_NCHANNELS)

/*GLOBALS*/

static constexpr float AUDIO_SAMPLEFACTOR = (float) (1 << (AUDIO_BITDEPTH - 1u));

extern uintptr_t AUDIO_SAMPLERATE;
extern uint64_t AUDIO_DATABEGIN;
extern uint64_t AUDIO_DATAEND;

extern void (*p_bufferload)(void);

#endif /*AUDIODELAYPB_DEF_H*/

